pipeline {
    agent {
        docker { 
            image 'cmendozat/jenkinsdocker-report:2211.44'
            args '-u root:sudo -v /var/lib/jenkins/workspace/docker-assets:/var/lib/jenkins/workspace/docker-assets:rw,z'
        }
    }
    stages {
        stage('checkout') {
            steps {
                sh '''
                    cd /opt/Alkosto_CCV2_2/alkosto-ccv2
                    git checkout release-d1
                    git pull
                '''
            }
        }
        stage('Install Node via NVM and Generate assets') {
            steps {
                sh '''
                    cd /opt/Alkosto_CCV2_2/alkosto-ccv2/core-customize/hybris/bin/custom/alkostostorefront/
                    apt-get install curl -y

                    # Instalar NVM
                    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

                    # Cargar NVM correctamente
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

                    # Instalar Node 22
                    nvm install 22

                    node -v
                    npm -v
                    npm install -g grunt-cli

                    npm install

                    grunt create-aws-assets --force
                    cd web/webroot/release/
                    ls -la
                '''
            }
        }
        stage('push assets package'){
            steps {
                sh '''
                    cd /opt
                    mkdir paquete-assets
                    cd paquete-assets
                    git clone https://cmendozat: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@github.com/cmendozat/jenkis-docker-assets.git
                    ls -la
                    cd jenkis-docker-assets

                    git remote set-url origin https://cmendozat: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@github.com/cmendozat/jenkis-docker-assets.git
                    git config user.email "carlos-jose0294@hotmail.com"
                    git config user.name "cmendozat"
                    git checkout dev
                    git pull

                    mv /opt/Alkosto_CCV2_2/alkosto-ccv2/core-customize/hybris/bin/custom/alkostostorefront/web/webroot/release/* .
                    ls -la
                    git add .
                    git commit -m "new package of assets generated by the pipeline"
                    git push origin dev
                '''
            }
        }
    }
}
